# Generated by Django 5.0.4 on 2024-05-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_file_user_active_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='workshop_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
