# Generated by Django 5.0.4 on 2024-05-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
    ]
